task1: task1.c
	gcc -o pattern task1.c

task2: task2.c
	gcc -o stopWatch task2.c

task3: task3.c
	gcc -o treasureHunt task3.c

task4: task4.c
	gcc -o population task4.c

task5: task5.c
	gcc -o imageProcessing task5.c

