task1: task1.c
	gcc -o address task1.c

task2: task2.c
	gcc -o systemCheck task2.c

task3: task3.c
	gcc -o functionTest task3.c -lm

task4: task4.c
	gcc -o textProcessing task4.c

task5: task5.c
	gcc -o matrix task5.c

