task1: task1.c
	gcc -o numbers task1.c

task2: task2.c
	gcc -o primeNumbers task2.c

task3: task3.c
	gcc -o cities task3.c

task4: task4.c
	gcc -o players task4.c

task5: task5.c
	gcc -o histogram task5.c
task6: task6.c
	gcc -o fibonacci task6.c
