task1: task1.c
	gcc -o axby task1.c

task2: task2.c
	gcc -o reverseString task2.c

task3: task3.c
	gcc -o dcShift task3.c 

task4: task4.c
	gcc -o stack task4.c

task5: task5.c
	gcc -o algebra task5.c

