task1: task1.c
	gcc -o students task1.c

task2: task2.c
	gcc -o counts task2.c

task3: task3.c
	gcc -o  hex task3.c -lm

task4: task4.c
	gcc -o encryption task4.c

task5: task5.c
	gcc -o books task5.c

